name: Backend CI

on:
  push:
    branches: [master, develop, feature/*, renovate/*, release/*]
    paths:
      - "backend/**"
  pull_request:
    branches: [master, develop, feature/*, renovate/*, release/*]
    paths:
      - "backend/**"

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
