name: Release

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Merge develop into master
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          source_ref: 'develop'
          target_branch: 'master'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
